apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-08-20T19:49:31Z
  generation: 2
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default
  resourceVersion: "904"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx-1
  uid: 2805a653-a4b2-11e8-a16d-42010a960fc7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - image: gcr.io/la-containers-001/la-container-image:v1
        imagePullPolicy: IfNotPresent
        name: la-container-image
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-08-20T19:49:38Z
    lastUpdateTime: 2018-08-20T19:49:38Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
